name: Deploy to Netlify

on:
  push:
    branches:
      - main  # A branch, amely triggereli a deploy-t

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Build Angular app
      run:  ng build --output-path=dist/vocation-tracker/browser --base-href=/

    - name: Deploy to Netlify
      run: netlify deploy --auth nfp_vC1ofprL6vwJXQwJobYyJxpWDtt4iQzT24a5 --prod --dir=dist/vocation-tracker/browser --site=37414b4c-edd1-4f7b-a6a6-224b036a17d0
